FROM debian:bookworm-slim AS prod

ARG LIBREOFFICE_VERSION=24.8.7
ARG LIBREOFFICE_VERSION_L2=24.8
ARG LIBREOFFICE_PYTHON=3.9.22

EXPOSE 8989

ENV PATH="/opt/libreoffice${LIBREOFFICE_VERSION_L2}/program/python-core-${LIBREOFFICE_PYTHON}/bin:$PATH"
ENV OO_VERSION=${LIBREOFFICE_VERSION_L2}

WORKDIR /tmp

# LibreOffice Tools
RUN apt-get update \
    && apt-get install --no-install-recommends -y -q \
        wget \
        # LibreOffice dependencies
        default-jre \
        libxinerama1 libnss3 libdbus-1-3 libxml2 libcairo2 libxslt1.1 libgio3.0-cil libcups2 libx11-xcb1 \
        # Other tools
        psmisc \
    # Install LibreOffice
    && wget https://download.documentfoundation.org/libreoffice/stable/${LIBREOFFICE_VERSION}/deb/x86_64/LibreOffice_${LIBREOFFICE_VERSION}_Linux_x86-64_deb.tar.gz \
    && tar -xzf LibreOffice_${LIBREOFFICE_VERSION}_Linux_x86-64_deb.tar.gz \
    && rm LibreOffice_${LIBREOFFICE_VERSION}_Linux_x86-64_deb.tar.gz \
    && dpkg -i LibreOffice_${LIBREOFFICE_VERSION}*_Linux_x86-64_deb/DEBS/*.deb \
    && rm -rf LibreOffice_${LIBREOFFICE_VERSION}*_Linux_x86-64_deb \
    # Install PIP
    && wget https://bootstrap.pypa.io/get-pip.py \
    && /opt/libreoffice${LIBREOFFICE_VERSION_L2}/program/python get-pip.py \
    && rm -f get-pip.py \
    && /opt/libreoffice${LIBREOFFICE_VERSION_L2}/program/python -m pip install --no-cache-dir jsonrpc2 \
    # Clean
    && apt-get purge -y -q wget \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && rm -rf /tmp/*

WORKDIR /app

RUN adduser -u 1000 --disabled-password --gecos "" appuser  \
    && chown -R appuser /app

COPY docker/entrypoint.sh /usr/local/bin/
COPY docker/officeLauncher.sh /usr/local/bin/

USER appuser

RUN mkdir -p /tmp/aeroo-docs

COPY src/* .
COPY docker/*.sh /usr/local/bin/

ENTRYPOINT ["entrypoint.sh"]

FROM prod AS dev

# Keeps Python from generating .pyc files in the container
ENV PYTHONDONTWRITEBYTECODE=1
# Turns off buffering for easier container logging
ENV PYTHONUNBUFFERED=1

USER root
# Dev tools
RUN apt-get update \
    && apt-get install --no-install-recommends -y -q \
        git \
        sudo \
        bash-completion \
        ssh-client \
        nano \
        gnupg2 \
        # Execute
        cpulimit \
        procps \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && /opt/libreoffice${LIBREOFFICE_VERSION_L2}/program/python -m pip install --no-cache-dir types-unopy

RUN echo "appuser     ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/appuser \
    && chmod 0440 /etc/sudoers.d/appuser

USER appuser
COPY docker/prompt.sh /home/appuser/.prompt.sh
RUN echo ". ~/.prompt.sh" >> ~/.bashrc

ENTRYPOINT []
CMD ["sleep", "infinity"]
